using NsbWeb.ReportingModule.ViewModels;

namespace NsbWeb.ReportingModule.QueryServices.Impl
{
    public class ExcelReportDataTranslator
    {
        public static ExcelReportData ToExcelReportData(UnitReportViewModel data)
        {
            return new ExcelReportData()
            {
                Id = data.Id,
                Description = data.Description,
                Organization = data.Organization,
                ReportingPeriod = data.ReportingPeriod,
                ReportStatus = data.ReportStatus,
                ReOpenedReportStatus = data.ReOpenedReportStatus,
                AssociateMemberData = data.AssociateMemberData,
                PreliminaryMemberData = data.PreliminaryMemberData,
                SupporterMemberData = data.SupporterMemberData,
                WorkerMeetingProgramData = data.WorkerMeetingProgramData,
                DawahMeetingProgramData = data.DawahMeetingProgramData,
                StateLeaderMeetingProgramData = data.StateLeaderMeetingProgramData,
                StateOutingMeetingProgramData = data.StateOutingMeetingProgramData,
                IftarMeetingProgramData = data.IftarMeetingProgramData,
                LearningMeetingProgramData = data.LearningMeetingProgramData,
                SocialDawahMeetingProgramData = data.SocialDawahMeetingProgramData,
                DawahGroupMeetingProgramData = data.DawahGroupMeetingProgramData,
                NextGMeetingProgramData = data.NextGMeetingProgramData,
                CmsMeetingProgramData = data.CmsMeetingProgramData,
                SmMeetingProgramData = data.SmMeetingProgramData,
                MemberMeetingProgramData = data.MemberMeetingProgramData,
                TafsirMeetingProgramData = data.TafsirMeetingProgramData,
                UnitMeetingProgramData = data.UnitMeetingProgramData,
                FamilyVisitMeetingProgramData = data.FamilyVisitMeetingProgramData,
                EidReunionMeetingProgramData = data.EidReunionMeetingProgramData,
                BbqMeetingProgramData = data.BbqMeetingProgramData,
                GatheringMeetingProgramData = data.GatheringMeetingProgramData,
                OtherMeetingProgramData = data.OtherMeetingProgramData,

                MemberMemberData = data.MemberMemberData,

                BaitulMalFinanceData = data.BaitulMalFinanceData,
                ADayMasjidProjectFinanceData = data.ADayMasjidProjectFinanceData,
                MasjidTableBankFinanceData = data.MasjidTableBankFinanceData,

                QardeHasanaSocialWelfareData = data.QardeHasanaSocialWelfareData,
                PatientVisitSocialWelfareData = data.PatientVisitSocialWelfareData,
                SocialVisitSocialWelfareData = data.SocialVisitSocialWelfareData,
                TransportSocialWelfareData = data.TransportSocialWelfareData,
                ShiftingSocialWelfareData = data.ShiftingSocialWelfareData,
                ShoppingSocialWelfareData = data.ShoppingSocialWelfareData,
                FoodDistributionSocialWelfareData = data.FoodDistributionSocialWelfareData,
                CleanUpAustraliaSocialWelfareData = data.CleanUpAustraliaSocialWelfareData,
                OtherSocialWelfareData = data.OtherSocialWelfareData,

                BookSaleMaterialData = data.BookSaleMaterialData,
                BookDistributionMaterialData = data.BookDistributionMaterialData,
                BookLibraryStockData = data.BookLibraryStockData,
                OtherSaleMaterialData = data.OtherSaleMaterialData,
                OtherDistributionMaterialData = data.OtherDistributionMaterialData,
                OtherLibraryStockData = data.OtherLibraryStockData,
                VhsSaleMaterialData = data.VhsSaleMaterialData,
                VhsDistributionMaterialData = data.VhsDistributionMaterialData,
                VhsLibraryStockData = data.VhsLibraryStockData,
                EmailDistributionMaterialData = data.EmailDistributionMaterialData,
                IpdcLeafletDistributionMaterialData = data.IpdcLeafletDistributionMaterialData,

                GroupStudyTeachingLearningProgramData = data.GroupStudyTeachingLearningProgramData,
                StudyCircleTeachingLearningProgramData = data.StudyCircleTeachingLearningProgramData,
                PracticeDarsTeachingLearningProgramData = data.PracticeDarsTeachingLearningProgramData,
                StateLearningCampTeachingLearningProgramData = data.StateLearningCampTeachingLearningProgramData,
                QuranStudyTeachingLearningProgramData = data.QuranStudyTeachingLearningProgramData,
                QuranClassTeachingLearningProgramData = data.QuranClassTeachingLearningProgramData,
                MemorizingAyatTeachingLearningProgramData = data.MemorizingAyatTeachingLearningProgramData,
                StateLearningSessionTeachingLearningProgramData = data.StateLearningSessionTeachingLearningProgramData,
                StateQiyamulLailTeachingLearningProgramData = data.StateQiyamulLailTeachingLearningProgramData,
                StudyCircleForAssociateMemberTeachingLearningProgramData = data.StudyCircleForAssociateMemberTeachingLearningProgramData,
                HadithTeachingLearningProgramData = data.HadithTeachingLearningProgramData,
                WeekendIslamicSchoolTeachingLearningProgramData = data.WeekendIslamicSchoolTeachingLearningProgramData,
                MemorizingHadithTeachingLearningProgramData = data.MemorizingHadithTeachingLearningProgramData,
                MemorizingDoaTeachingLearningProgramData = data.MemorizingDoaTeachingLearningProgramData,
                OtherTeachingLearningProgramData = data.OtherTeachingLearningProgramData,

                Comment = data.Comment,
                Timestamp = data.Timestamp,
            };
        }
        public static ExcelReportData ToExcelReportData(ZoneReportViewModel data)
        {
            return new ExcelReportData()
            {
                Id = data.Id,
                Description = data.Description,
                Organization = data.Organization,
                ReportingPeriod = data.ReportingPeriod,
                ReportStatus = data.ReportStatus,
                ReOpenedReportStatus = data.ReOpenedReportStatus,
                AssociateMemberData = data.AssociateMemberData,
                PreliminaryMemberData = data.PreliminaryMemberData,
                SupporterMemberData = data.SupporterMemberData,
                WorkerMeetingProgramData = data.WorkerMeetingProgramData,
                DawahMeetingProgramData = data.DawahMeetingProgramData,
                StateLeaderMeetingProgramData = data.StateLeaderMeetingProgramData,
                StateOutingMeetingProgramData = data.StateOutingMeetingProgramData,
                IftarMeetingProgramData = data.IftarMeetingProgramData,
                LearningMeetingProgramData = data.LearningMeetingProgramData,
                SocialDawahMeetingProgramData = data.SocialDawahMeetingProgramData,
                DawahGroupMeetingProgramData = data.DawahGroupMeetingProgramData,
                NextGMeetingProgramData = data.NextGMeetingProgramData,
                CmsMeetingProgramData = data.CmsMeetingProgramData,
                SmMeetingProgramData = data.SmMeetingProgramData,
                MemberMeetingProgramData = data.MemberMeetingProgramData,
                TafsirMeetingProgramData = data.TafsirMeetingProgramData,
                UnitMeetingProgramData = data.UnitMeetingProgramData,
                FamilyVisitMeetingProgramData = data.FamilyVisitMeetingProgramData,
                EidReunionMeetingProgramData = data.EidReunionMeetingProgramData,
                BbqMeetingProgramData = data.BbqMeetingProgramData,
                GatheringMeetingProgramData = data.GatheringMeetingProgramData,
                OtherMeetingProgramData = data.OtherMeetingProgramData,

                MemberMemberData = data.MemberMemberData,

                BaitulMalFinanceData = data.BaitulMalFinanceData,
                ADayMasjidProjectFinanceData = data.ADayMasjidProjectFinanceData,
                MasjidTableBankFinanceData = data.MasjidTableBankFinanceData,

                QardeHasanaSocialWelfareData = data.QardeHasanaSocialWelfareData,
                PatientVisitSocialWelfareData = data.PatientVisitSocialWelfareData,
                SocialVisitSocialWelfareData = data.SocialVisitSocialWelfareData,
                TransportSocialWelfareData = data.TransportSocialWelfareData,
                ShiftingSocialWelfareData = data.ShiftingSocialWelfareData,
                ShoppingSocialWelfareData = data.ShoppingSocialWelfareData,
                FoodDistributionSocialWelfareData = data.FoodDistributionSocialWelfareData,
                CleanUpAustraliaSocialWelfareData = data.CleanUpAustraliaSocialWelfareData,
                OtherSocialWelfareData = data.OtherSocialWelfareData,

                BookSaleMaterialData = data.BookSaleMaterialData,
                BookDistributionMaterialData = data.BookDistributionMaterialData,
                BookLibraryStockData = data.BookLibraryStockData,
                OtherSaleMaterialData = data.OtherSaleMaterialData,
                OtherDistributionMaterialData = data.OtherDistributionMaterialData,
                OtherLibraryStockData = data.OtherLibraryStockData,
                VhsSaleMaterialData = data.VhsSaleMaterialData,
                VhsDistributionMaterialData = data.VhsDistributionMaterialData,
                VhsLibraryStockData = data.VhsLibraryStockData,
                EmailDistributionMaterialData = data.EmailDistributionMaterialData,
                IpdcLeafletDistributionMaterialData = data.IpdcLeafletDistributionMaterialData,

                GroupStudyTeachingLearningProgramData = data.GroupStudyTeachingLearningProgramData,
                StudyCircleTeachingLearningProgramData = data.StudyCircleTeachingLearningProgramData,
                PracticeDarsTeachingLearningProgramData = data.PracticeDarsTeachingLearningProgramData,
                StateLearningCampTeachingLearningProgramData = data.StateLearningCampTeachingLearningProgramData,
                QuranStudyTeachingLearningProgramData = data.QuranStudyTeachingLearningProgramData,
                QuranClassTeachingLearningProgramData = data.QuranClassTeachingLearningProgramData,
                MemorizingAyatTeachingLearningProgramData = data.MemorizingAyatTeachingLearningProgramData,
                StateLearningSessionTeachingLearningProgramData = data.StateLearningSessionTeachingLearningProgramData,
                StateQiyamulLailTeachingLearningProgramData = data.StateQiyamulLailTeachingLearningProgramData,
                StudyCircleForAssociateMemberTeachingLearningProgramData = data.StudyCircleForAssociateMemberTeachingLearningProgramData,
                HadithTeachingLearningProgramData = data.HadithTeachingLearningProgramData,
                WeekendIslamicSchoolTeachingLearningProgramData = data.WeekendIslamicSchoolTeachingLearningProgramData,
                MemorizingHadithTeachingLearningProgramData = data.MemorizingHadithTeachingLearningProgramData,
                MemorizingDoaTeachingLearningProgramData = data.MemorizingDoaTeachingLearningProgramData,
                OtherTeachingLearningProgramData = data.OtherTeachingLearningProgramData,

                Comment = data.Comment,
                Timestamp = data.Timestamp,
            };
        }
        public static ExcelReportData ToExcelReportData(StateReportViewModel data)
        {
            return new ExcelReportData()
            {
                Id = data.Id,
                Description = data.Description,
                Organization = data.Organization,
                ReportingPeriod = data.ReportingPeriod,
                ReportStatus = data.ReportStatus,
                ReOpenedReportStatus = data.ReOpenedReportStatus,
                AssociateMemberData = data.AssociateMemberData,
                PreliminaryMemberData = data.PreliminaryMemberData,
                SupporterMemberData = data.SupporterMemberData,
                WorkerMeetingProgramData = data.WorkerMeetingProgramData,
                DawahMeetingProgramData = data.DawahMeetingProgramData,
                StateLeaderMeetingProgramData = data.StateLeaderMeetingProgramData,
                StateOutingMeetingProgramData = data.StateOutingMeetingProgramData,
                IftarMeetingProgramData = data.IftarMeetingProgramData,
                LearningMeetingProgramData = data.LearningMeetingProgramData,
                SocialDawahMeetingProgramData = data.SocialDawahMeetingProgramData,
                DawahGroupMeetingProgramData = data.DawahGroupMeetingProgramData,
                NextGMeetingProgramData = data.NextGMeetingProgramData,
                CmsMeetingProgramData = data.CmsMeetingProgramData,
                SmMeetingProgramData = data.SmMeetingProgramData,
                MemberMeetingProgramData = data.MemberMeetingProgramData,
                TafsirMeetingProgramData = data.TafsirMeetingProgramData,
                UnitMeetingProgramData = data.UnitMeetingProgramData,
                FamilyVisitMeetingProgramData = data.FamilyVisitMeetingProgramData,
                EidReunionMeetingProgramData = data.EidReunionMeetingProgramData,
                BbqMeetingProgramData = data.BbqMeetingProgramData,
                GatheringMeetingProgramData = data.GatheringMeetingProgramData,
                OtherMeetingProgramData = data.OtherMeetingProgramData,

                MemberMemberData = data.MemberMemberData,

                BaitulMalFinanceData = data.BaitulMalFinanceData,
                ADayMasjidProjectFinanceData = data.ADayMasjidProjectFinanceData,
                MasjidTableBankFinanceData = data.MasjidTableBankFinanceData,

                QardeHasanaSocialWelfareData = data.QardeHasanaSocialWelfareData,
                PatientVisitSocialWelfareData = data.PatientVisitSocialWelfareData,
                SocialVisitSocialWelfareData = data.SocialVisitSocialWelfareData,
                TransportSocialWelfareData = data.TransportSocialWelfareData,
                ShiftingSocialWelfareData = data.ShiftingSocialWelfareData,
                ShoppingSocialWelfareData = data.ShoppingSocialWelfareData,
                FoodDistributionSocialWelfareData = data.FoodDistributionSocialWelfareData,
                CleanUpAustraliaSocialWelfareData = data.CleanUpAustraliaSocialWelfareData,
                OtherSocialWelfareData = data.OtherSocialWelfareData,

                BookSaleMaterialData = data.BookSaleMaterialData,
                BookDistributionMaterialData = data.BookDistributionMaterialData,
                BookLibraryStockData = data.BookLibraryStockData,
                OtherSaleMaterialData = data.OtherSaleMaterialData,
                OtherDistributionMaterialData = data.OtherDistributionMaterialData,
                OtherLibraryStockData = data.OtherLibraryStockData,
                VhsSaleMaterialData = data.VhsSaleMaterialData,
                VhsDistributionMaterialData = data.VhsDistributionMaterialData,
                VhsLibraryStockData = data.VhsLibraryStockData,
                EmailDistributionMaterialData = data.EmailDistributionMaterialData,
                IpdcLeafletDistributionMaterialData = data.IpdcLeafletDistributionMaterialData,

                GroupStudyTeachingLearningProgramData = data.GroupStudyTeachingLearningProgramData,
                StudyCircleTeachingLearningProgramData = data.StudyCircleTeachingLearningProgramData,
                PracticeDarsTeachingLearningProgramData = data.PracticeDarsTeachingLearningProgramData,
                StateLearningCampTeachingLearningProgramData = data.StateLearningCampTeachingLearningProgramData,
                QuranStudyTeachingLearningProgramData = data.QuranStudyTeachingLearningProgramData,
                QuranClassTeachingLearningProgramData = data.QuranClassTeachingLearningProgramData,
                MemorizingAyatTeachingLearningProgramData = data.MemorizingAyatTeachingLearningProgramData,
                StateLearningSessionTeachingLearningProgramData = data.StateLearningSessionTeachingLearningProgramData,
                StateQiyamulLailTeachingLearningProgramData = data.StateQiyamulLailTeachingLearningProgramData,
                StudyCircleForAssociateMemberTeachingLearningProgramData = data.StudyCircleForAssociateMemberTeachingLearningProgramData,
                HadithTeachingLearningProgramData = data.HadithTeachingLearningProgramData,
                WeekendIslamicSchoolTeachingLearningProgramData = data.WeekendIslamicSchoolTeachingLearningProgramData,
                MemorizingHadithTeachingLearningProgramData = data.MemorizingHadithTeachingLearningProgramData,
                MemorizingDoaTeachingLearningProgramData = data.MemorizingDoaTeachingLearningProgramData,
                OtherTeachingLearningProgramData = data.OtherTeachingLearningProgramData,

                Comment = data.Comment,
                Timestamp = data.Timestamp,
            };
        }
        public static ExcelReportData ToExcelReportData(CentralReportViewModel data)
        {
            return new ExcelReportData()
            {
                Id = data.Id,
                Description = data.Description,
                Organization = data.Organization,
                ReportingPeriod = data.ReportingPeriod,
                ReportStatus = data.ReportStatus,
                ReOpenedReportStatus = data.ReOpenedReportStatus,
                AssociateMemberData = data.AssociateMemberData,
                PreliminaryMemberData = data.PreliminaryMemberData,
                SupporterMemberData = data.SupporterMemberData,
                WorkerMeetingProgramData = data.WorkerMeetingProgramData,
                DawahMeetingProgramData = data.DawahMeetingProgramData,
                StateLeaderMeetingProgramData = data.StateLeaderMeetingProgramData,
                StateOutingMeetingProgramData = data.StateOutingMeetingProgramData,
                IftarMeetingProgramData = data.IftarMeetingProgramData,
                LearningMeetingProgramData = data.LearningMeetingProgramData,
                SocialDawahMeetingProgramData = data.SocialDawahMeetingProgramData,
                DawahGroupMeetingProgramData = data.DawahGroupMeetingProgramData,
                NextGMeetingProgramData = data.NextGMeetingProgramData,
                CmsMeetingProgramData = data.CmsMeetingProgramData,
                SmMeetingProgramData = data.SmMeetingProgramData,
                MemberMeetingProgramData = data.MemberMeetingProgramData,
                TafsirMeetingProgramData = data.TafsirMeetingProgramData,
                UnitMeetingProgramData = data.UnitMeetingProgramData,
                FamilyVisitMeetingProgramData = data.FamilyVisitMeetingProgramData,
                EidReunionMeetingProgramData = data.EidReunionMeetingProgramData,
                BbqMeetingProgramData = data.BbqMeetingProgramData,
                GatheringMeetingProgramData = data.GatheringMeetingProgramData,
                OtherMeetingProgramData = data.OtherMeetingProgramData,

                MemberMemberData = data.MemberMemberData,

                BaitulMalFinanceData = data.BaitulMalFinanceData,
                ADayMasjidProjectFinanceData = data.ADayMasjidProjectFinanceData,
                MasjidTableBankFinanceData = data.MasjidTableBankFinanceData,

                QardeHasanaSocialWelfareData = data.QardeHasanaSocialWelfareData,
                PatientVisitSocialWelfareData = data.PatientVisitSocialWelfareData,
                SocialVisitSocialWelfareData = data.SocialVisitSocialWelfareData,
                TransportSocialWelfareData = data.TransportSocialWelfareData,
                ShiftingSocialWelfareData = data.ShiftingSocialWelfareData,
                ShoppingSocialWelfareData = data.ShoppingSocialWelfareData,
                FoodDistributionSocialWelfareData = data.FoodDistributionSocialWelfareData,
                CleanUpAustraliaSocialWelfareData = data.CleanUpAustraliaSocialWelfareData,
                OtherSocialWelfareData = data.OtherSocialWelfareData,

                BookSaleMaterialData = data.BookSaleMaterialData,
                BookDistributionMaterialData = data.BookDistributionMaterialData,
                BookLibraryStockData = data.BookLibraryStockData,
                OtherSaleMaterialData = data.OtherSaleMaterialData,
                OtherDistributionMaterialData = data.OtherDistributionMaterialData,
                OtherLibraryStockData = data.OtherLibraryStockData,
                VhsSaleMaterialData = data.VhsSaleMaterialData,
                VhsDistributionMaterialData = data.VhsDistributionMaterialData,
                VhsLibraryStockData = data.VhsLibraryStockData,
                EmailDistributionMaterialData = data.EmailDistributionMaterialData,
                IpdcLeafletDistributionMaterialData = data.IpdcLeafletDistributionMaterialData,

                GroupStudyTeachingLearningProgramData = data.GroupStudyTeachingLearningProgramData,
                StudyCircleTeachingLearningProgramData = data.StudyCircleTeachingLearningProgramData,
                PracticeDarsTeachingLearningProgramData = data.PracticeDarsTeachingLearningProgramData,
                StateLearningCampTeachingLearningProgramData = data.StateLearningCampTeachingLearningProgramData,
                QuranStudyTeachingLearningProgramData = data.QuranStudyTeachingLearningProgramData,
                QuranClassTeachingLearningProgramData = data.QuranClassTeachingLearningProgramData,
                MemorizingAyatTeachingLearningProgramData = data.MemorizingAyatTeachingLearningProgramData,
                StateLearningSessionTeachingLearningProgramData = data.StateLearningSessionTeachingLearningProgramData,
                StateQiyamulLailTeachingLearningProgramData = data.StateQiyamulLailTeachingLearningProgramData,
                StudyCircleForAssociateMemberTeachingLearningProgramData = data.StudyCircleForAssociateMemberTeachingLearningProgramData,
                HadithTeachingLearningProgramData = data.HadithTeachingLearningProgramData,
                WeekendIslamicSchoolTeachingLearningProgramData = data.WeekendIslamicSchoolTeachingLearningProgramData,
                MemorizingHadithTeachingLearningProgramData = data.MemorizingHadithTeachingLearningProgramData,
                MemorizingDoaTeachingLearningProgramData = data.MemorizingDoaTeachingLearningProgramData,
                OtherTeachingLearningProgramData = data.OtherTeachingLearningProgramData,

                Comment = data.Comment,
                Timestamp = data.Timestamp,
            };
        }
    }
}
