EXEC sp_rename 'CMSMeetingData', 'CmsMeetingData'
EXEC sp_rename 'CMSMeetingGeneratedData', 'CmsMeetingGeneratedData'
EXEC sp_rename 'SMMeetingData', 'SmMeetingData'
EXEC sp_rename 'SMMeetingGeneratedData', 'SmMeetingGeneratedData'
EXEC sp_rename 'BBQMeetingData', 'BbqMeetingData'
EXEC sp_rename 'BBQMeetingGeneratedData', 'BbqMeetingGeneratedData'