DROP INDEX index_adaymasjidprojectfinancedata_reportid ON dbo.ADayMasjidProjectFinanceData
GO
DROP INDEX index_adaymasjidprojectfinancegenerateddata_reportid ON dbo.ADayMasjidProjectFinanceGeneratedData
GO
DROP INDEX index_associatememberdata_reportid ON dbo.AssociateMemberData
GO
DROP INDEX index_associatemembergenerateddata_reportid ON dbo.AssociateMemberGeneratedData
GO
DROP INDEX index_baitulmalfinancedata_reportid ON dbo.BaitulMalFinanceData
GO
DROP INDEX index_baitulmalfinancegenerateddata_reportid ON dbo.BaitulMalFinanceGeneratedData
GO
DROP INDEX index_bbqmeetingdata_reportid ON dbo.BbqMeetingData
GO
DROP INDEX index_bbqmeetinggenerateddata_reportid ON dbo.BbqMeetingGeneratedData
GO
DROP INDEX index_bookdistributionmaterialdata_reportid ON dbo.BookDistributionMaterialData
GO
DROP INDEX index_bookdistributionmaterialgenerateddata_reportid ON dbo.BookDistributionMaterialGeneratedData
GO
DROP INDEX index_booklibrarystockdata_reportid ON dbo.BookLibraryStockData
GO
DROP INDEX index_booklibrarystockgenerateddata_reportid ON dbo.BookLibraryStockGeneratedData
GO
DROP INDEX index_booksalematerialdata_reportid ON dbo.BookSaleMaterialData
GO
DROP INDEX index_booksalematerialgenerateddata_reportid ON dbo.BookSaleMaterialGeneratedData
GO
DROP INDEX index_cmsmeetingdata_reportid ON dbo.CmsMeetingData
GO
DROP INDEX index_cmsmeetinggenerateddata_reportid ON dbo.CmsMeetingGeneratedData
GO
DROP INDEX index_dawahgroupmeetingdata_reportid ON dbo.DawahGroupMeetingData
GO
DROP INDEX index_dawahgroupmeetinggenerateddata_reportid ON dbo.DawahGroupMeetingGeneratedData
GO
DROP INDEX index_dawahmeetingdata_reportid ON dbo.DawahMeetingData
GO
DROP INDEX index_dawahmeetinggenerateddata_reportid ON dbo.DawahMeetingGeneratedData
GO
DROP INDEX index_eidreunionmeetingdata_reportid ON dbo.EidReunionMeetingData
GO
DROP INDEX index_eidreunionmeetinggenerateddata_reportid ON dbo.EidReunionMeetingGeneratedData
GO
DROP INDEX index_emaildistributionmaterialdata_reportid ON dbo.EmailDistributionMaterialData
GO
DROP INDEX index_emaildistributionmaterialgenerateddata_reportid ON dbo.EmailDistributionMaterialGeneratedData
GO
DROP INDEX index_familyvisitmeetingdata_reportid ON dbo.FamilyVisitMeetingData
GO
DROP INDEX index_familyvisitmeetinggenerateddata_reportid ON dbo.FamilyVisitMeetingGeneratedData
GO
DROP INDEX index_fooddistributionsocialwelfaredata_reportid ON dbo.FoodDistributionSocialWelfareData
GO
DROP INDEX index_fooddistributionsocialwelfaregenerateddata_reportid ON dbo.FoodDistributionSocialWelfareGeneratedData
GO
DROP INDEX index_gatheringmeetingdata_reportid ON dbo.GatheringMeetingData
GO
DROP INDEX index_gatheringmeetinggenerateddata_reportid ON dbo.GatheringMeetingGeneratedData
GO
DROP INDEX index_groupstudyteachinglearningprogramdata_reportid ON dbo.GroupStudyTeachingLearningProgramData
GO
DROP INDEX index_groupstudyteachinglearningprogramgenerateddata_reportid ON dbo.GroupStudyTeachingLearningProgramGeneratedData
GO
DROP INDEX index_hadithteachinglearning_reportid ON dbo.HadithTeachingLearningProgramData
GO
DROP INDEX index_hadithteachinglearninggenerateddata_reportid ON dbo.HadithTeachingLearningProgramGeneratedData
GO
DROP INDEX index_iftarmeetingdata_reportid ON dbo.IftarMeetingData
GO
DROP INDEX index_iftarmeetinggenerateddata_reportid ON dbo.IftarMeetingGeneratedData
GO
DROP INDEX index_ipdcleafletdistributionmaterialdata_reportid ON dbo.IpdcLeafletDistributionMaterialData
GO
DROP INDEX index_ipdcleafletdistributionmaterialgenerateddata_reportid ON dbo.IpdcLeafletDistributionMaterialGeneratedData
GO
DROP INDEX index_learningmeetingdata_reportid ON dbo.LearningMeetingData
GO
DROP INDEX index_learningmeetinggenerateddata_reportid ON dbo.LearningMeetingGeneratedData
GO
DROP INDEX index_masjidtablebankfinancedata_reportid ON dbo.MasjidTableBankFinanceData
GO
DROP INDEX index_masjidtablebankfinancegenerateddata_reportid ON dbo.MasjidTableBankFinanceGeneratedData
GO
DROP INDEX index_membermeetingdata_reportid ON dbo.MemberMeetingData
GO
DROP INDEX index_membermeetinggenerateddata_reportid ON dbo.MemberMeetingGeneratedData
GO
DROP INDEX index_membermemberdata_reportid ON dbo.MemberMemberData
GO
DROP INDEX index_membermembergenerateddata_reportid ON dbo.MemberMemberGeneratedData
GO
DROP INDEX index_memorizingayatteachinglearningprogramdata_reportid ON dbo.MemorizingAyatTeachingLearningProgramData
GO
DROP INDEX index_memorizingayatteachinglearningprogramgenerateddata_reportid ON dbo.MemorizingAyatTeachingLearningProgramGeneratedData
GO
DROP INDEX index_memorizingdoateachinglearning_reportid ON dbo.MemorizingDoaTeachingLearningProgramData
GO
DROP INDEX index_memorizingdoateachinglearninggenerateddata_reportid ON dbo.MemorizingDoaTeachingLearningProgramGeneratedData
GO
DROP INDEX index_memorizinghadithgenerateddata_reportid ON dbo.MemorizingHadithTeachingLearningProgramGeneratedData
GO
DROP INDEX index_memorizinghadithteachinglearning_reportid ON dbo.MemorizingHadithTeachingLearningProgramData
GO
DROP INDEX index_nextgmeetingdata_reportid ON dbo.NextGMeetingData
GO
DROP INDEX index_nextgmeetinggenerateddata_reportid ON dbo.NextGMeetingGeneratedData
GO
DROP INDEX index_otherdistributionmaterialdata_reportid ON dbo.OtherDistributionMaterialData
GO
DROP INDEX index_otherdistributionmaterialgenerateddata_reportid ON dbo.OtherDistributionMaterialGeneratedData
GO
DROP INDEX index_otherlibrarystockdata_reportid ON dbo.OtherLibraryStockData
GO
DROP INDEX index_otherlibrarystockgenerateddata_reportid ON dbo.OtherLibraryStockGeneratedData
GO
DROP INDEX index_othermeetingdata_reportid ON dbo.OtherMeetingData
GO
DROP INDEX index_othermeetinggenerateddata_reportid ON dbo.OtherMeetingGeneratedData
GO
DROP INDEX index_othersalematerialdata_reportid ON dbo.OtherSaleMaterialData
GO
DROP INDEX index_othersalematerialgenerateddata_reportid ON dbo.OtherSaleMaterialGeneratedData
GO
DROP INDEX index_othersocialwelfaredata_reportid ON dbo.OtherSocialWelfareData
GO
DROP INDEX index_othersocialwelfaregenerateddata_reportid ON dbo.OtherSocialWelfareGeneratedData
GO
DROP INDEX index_otherteachinglearningprogramdata_reportid ON dbo.OtherTeachingLearningProgramData
GO
DROP INDEX index_otherteachinglearningprogramgenerateddata_reportid ON dbo.OtherTeachingLearningProgramGeneratedData
GO
DROP INDEX index_patientvisitsocialwelfaredata_reportid ON dbo.PatientVisitSocialWelfareData
GO
DROP INDEX index_patientvisitsocialwelfaregenerateddata_reportid ON dbo.PatientVisitSocialWelfareGeneratedData
GO
DROP INDEX index_practicedarsteachinglearningprogramdata_reportid ON dbo.PracticeDarsTeachingLearningProgramData
GO
DROP INDEX index_practicedarsteachinglearningprogramgenerateddata_reportid ON dbo.PracticeDarsTeachingLearningProgramGeneratedData
GO
DROP INDEX index_preliminarymemberdata_reportid ON dbo.PreliminaryMemberData
GO
DROP INDEX index_preliminarymembergenerateddata_reportid ON dbo.PreliminaryMemberGeneratedData
GO
DROP INDEX index_qardehasanasocialwelfaredata_reportid ON dbo.QardeHasanaSocialWelfareData
GO
DROP INDEX index_qardehasanasocialwelfaregenerateddata_reportid ON dbo.QardeHasanaSocialWelfareGeneratedData
GO
DROP INDEX index_quranclassteachinglearningprogramdata_reportid ON dbo.QuranClassTeachingLearningProgramData
GO
DROP INDEX index_quranclassteachinglearningprogramgenerateddata_reportid ON dbo.QuranClassTeachingLearningProgramGeneratedData
GO
DROP INDEX index_quranstudyteachinglearningprogramdata_reportid ON dbo.QuranStudyTeachingLearningProgramData
GO
DROP INDEX index_quranstudyteachinglearningprogramgenerateddata_reportid ON dbo.QuranStudyTeachingLearningProgramGeneratedData
GO
DROP INDEX index_reporteventlog_reportid ON dbo.ReportEventLog
GO
DROP INDEX index_shiftingsocialwelfaredata_reportid ON dbo.ShiftingSocialWelfareData
GO
DROP INDEX index_shiftingsocialwelfaregenerateddata_reportid ON dbo.ShiftingSocialWelfareGeneratedData
GO
DROP INDEX index_shoppingsocialwelfaredata_reportid ON dbo.ShoppingSocialWelfareData
GO
DROP INDEX index_shoppingsocialwelfaregenerateddata_reportid ON dbo.ShoppingSocialWelfareGeneratedData
GO
DROP INDEX index_smmeetingdata_reportid ON dbo.SmMeetingData
GO
DROP INDEX index_smmeetinggenerateddata_reportid ON dbo.SmMeetingGeneratedData
GO
DROP INDEX index_socialdawahmeetingdata_reportid ON dbo.SocialDawahMeetingData
GO
DROP INDEX index_socialdawahmeetinggenerateddata_reportid ON dbo.SocialDawahMeetingGeneratedData
GO
DROP INDEX index_socialvisitsocialwelfaredata_reportid ON dbo.SocialVisitSocialWelfareData
GO
DROP INDEX index_socialvisitsocialwelfaregenerateddata_reportid ON dbo.SocialVisitSocialWelfareGeneratedData
GO
DROP INDEX index_stateleadermeetingdata_reportid ON dbo.StateLeaderMeetingData
GO
DROP INDEX index_stateleadermeetinggenerateddata_reportid ON dbo.StateLeaderMeetingGeneratedData
GO
DROP INDEX index_statelearningcampteachinglearningprogramdata_reportid ON dbo.StateLearningCampTeachingLearningProgramData
GO
DROP INDEX index_statelearningcampteachinglearningprogramgenerateddata_reportid ON dbo.StateLearningCampTeachingLearningProgramGeneratedData
GO
DROP INDEX index_statelearningsessionteachinglearningprogramdata_reportid ON dbo.StateLearningSessionTeachingLearningProgramData
GO
DROP INDEX index_statelearningsessionteachinglearningprogramgenerateddata_reportid ON dbo.StateLearningSessionTeachingLearningProgramGeneratedData
GO
DROP INDEX index_stateoutingmeetingdata_reportid ON dbo.StateOutingMeetingData
GO
DROP INDEX index_stateoutingmeetinggenerateddata_reportid ON dbo.StateOutingMeetingGeneratedData
GO
DROP INDEX index_stateqiyamullailteachinglearningprogramdata_reportid ON dbo.StateQiyamulLailTeachingLearningProgramData
GO
DROP INDEX index_stateqiyamullailteachinglearningprogramgenerateddata_reportid ON dbo.StateQiyamulLailTeachingLearningProgramGeneratedData
GO
DROP INDEX index_studycircleforassociatemembergenerateddata_reportid ON dbo.StudyCircleForAssociateMemberTeachingLearningProgramGeneratedData
GO
DROP INDEX index_studycircleforassociatememberteachinglearning_reportid ON dbo.StudyCircleForAssociateMemberTeachingLearningProgramData
GO
DROP INDEX index_studycircleteachinglearningprogramdata_reportid ON dbo.StudyCircleTeachingLearningProgramData
GO
DROP INDEX index_studycircleteachinglearningprogramgenerateddata_reportid ON dbo.StudyCircleTeachingLearningProgramGeneratedData
GO
DROP INDEX index_supportermemberdata_reportid ON dbo.SupporterMemberData
GO
DROP INDEX index_supportermembergenerateddata_reportid ON dbo.SupporterMemberGeneratedData
GO
DROP INDEX index_tafsirmeetingdata_reportid ON dbo.TafsirMeetingData
GO
DROP INDEX index_tafsirmeetinggenerateddata_reportid ON dbo.TafsirMeetingGeneratedData
GO
DROP INDEX index_transportsocialwelfaredata_reportid ON dbo.TransportSocialWelfareData
GO
DROP INDEX index_transportsocialwelfaregenerateddata_reportid ON dbo.TransportSocialWelfareGeneratedData
GO
DROP INDEX index_unitmeetingdata_reportid ON dbo.UnitMeetingData
GO
DROP INDEX index_unitmeetinggenerateddata_reportid ON dbo.UnitMeetingGeneratedData
GO
DROP INDEX index_vhsdistributionmaterialdata_reportid ON dbo.VhsDistributionMaterialData
GO
DROP INDEX index_vhsdistributionmaterialgenerateddata_reportid ON dbo.VhsDistributionMaterialGeneratedData
GO
DROP INDEX index_vhslibrarystockdata_reportid ON dbo.VhsLibraryStockData
GO
DROP INDEX index_vhslibrarystockgenerateddata_reportid ON dbo.VhsLibraryStockGeneratedData
GO
DROP INDEX index_vhssalematerialdata_reportid ON dbo.VhsSaleMaterialData
GO
DROP INDEX index_vhssalematerialgenerateddata_reportid ON dbo.VhsSaleMaterialGeneratedData
GO
DROP INDEX index_weekendislamicschoolteachinglearning_reportid ON dbo.WeekendIslamicSchoolTeachingLearningProgramData
GO
DROP INDEX index_weekendislamicschoolteachinglearninggenerateddata_reportid ON dbo.WeekendIslamicSchoolTeachingLearningProgramGeneratedData
GO
DROP INDEX index_workermeetingdata_reportid ON dbo.WorkerMeetingData
GO
DROP INDEX index_workermeetinggenerateddata_reportid ON dbo.WorkerMeetingGeneratedData
GO
