namespace ReportingModule.Core
{
	public enum Currency
	{
		AED = 1, //	United Arab Emirates, Dirhams                     
		AFA = 2, //	Afghanistan, Afghanis                             
		ALL = 3, //	Albania, Leke                                     
		AMD = 4, //	Armenia, Drams                                    
		ANG = 5, //	Netherlands Antilles, Guilders                    
		AOA = 6, //	Angola, Kwanza                                    
		ARS = 7, //	Argentina, Pesos                                  
		AUD = 8, //	Australia, Dollars                                
		AWG = 9, //	Aruba, Guilders                                   
		AZM = 10, //	Azerbaijan, Manats                                
		BAM = 11, //	Bosnia and Herzegovina, Convertible               
		BBD = 12, //	Barbados, Dollars                                 
		BDT = 13, //	Bangladesh, Taka                                  
		BGL = 14, //	Bulgaria, Leva                                    
		BHD = 15, //	Bahrain, Dinars                                   
		BIF = 16, //	Burundi, Francs                                   
		BMD = 17, //	Bermuda, Dollars                                  
		BND = 18, //	Brunei Darussalam, Dollars                        
		BOB = 19, //	Bolivia, Bolivianos                               
		BRL = 20, //	Brazil, Brazil Real                               
		BSD = 21, //	Bahamas, Dollars                                  
		BTN = 22, //	Bhutan, Ngultrum                                  
		BWP = 23, //	Botswana, Pulas                                   
		BYR = 24, //	Belarus, Rubles                                   
		BZD = 25, //	Belize, Dollars                                   
		CAD = 26, //	Canada, Dollars                                   
		CDF = 27, //	Congo/Kinshasa, Congolese Francs                  
		CHF = 28, //	Switzerland, Francs                               
		CLP = 29, //	Chile, Pesos                                      
		CNY = 30, //	China, Yuan Renminbi                              
		COP = 31, //	Colombia, Pesos                                   
		CRC = 32, //	Costa Rica, Colones                               
		CUP = 33, //	Cuba, Pesos                                       
		CVE = 34, //	Cape Verde, Escudos                               
		CYP = 35, //	Cyprus, Pounds                                    
		CZK = 36, //	Czech Republic, Koruny                            
		DJF = 37, //	Djibouti, Francs                                  
		DKK = 38, //	Denmark, Kroner                                   
		DOP = 39, //	Dominican Republic, Pesos                         
		DZD = 40, //	Algeria, Algeria Dinars                           
		EEK = 41, //	Estonia, Krooni                                   
		EGP = 42, //	Egypt, Pounds                                     
		ERN = 43, //	Eritrea, Nakfa                                    
		ETB = 44, //	Ethiopia, Birr                                    
		EUR = 45, //	Euro Member Countries, Euro                       
		FJD = 46, //	Fiji, Dollars                                     
		FKP = 47, //	Falkland Islands (Malvinas), Pounds               
		GBP = 48, //	United Kingdom, Pounds                            
		GEL = 49, //	Georgia, Lari                                     
		GHC = 50, //	Ghana, Cedis                                      
		GIP = 51, //	Gibraltar, Pounds                                 
		GMD = 52, //	Gambia, Dalasi                                    
		GNF = 53, //	Guinea, Francs                                    
		GTQ = 54, //	Guatemala, Quetzales                              
		GYD = 55, //	Guyana, Dollars                                   
		HKD = 56, //	Hong Kong, Dollars                                
		HNL = 57, //	Honduras, Lempiras                                
		HRK = 58, //	Croatia, Kuna                                     
		HTG = 59, //	Haiti, Gourdes                                    
		HUF = 60, //	Hungary, Forint                                   
		IDR = 61, //	Indonesia, Rupiahs                                
		ILS = 62, //	Israel, New Shekels                               
		INR = 63, //	India, Rupees                                     
		IQD = 64, //	Iraq, Dinars                                      
		IRR = 65, //	Iran, Rials                                       
		ISK = 66, //	Iceland, Kronur                                   
		JMD = 67, //	Jamaica, Dollars                                  
		JOD = 68, //	Jordan, Dinars                                    
		JPY = 69, //	Japan, Yen                                        
		KES = 70, //	Kenya, Shillings                                  
		KGS = 71, //	Kyrgyzstan, Soms                                  
		KHR = 72, //	Cambodia, Riels                                   
		KMF = 73, //	Comoros, Francs                                   
		KPW = 74, //	Korea (North), Won                                
		KRW = 75, //	Korea (South), Won                                
		KWD = 76, //	Kuwait, Dinars                                    
		KYD = 77, //	Cayman Islands, Dollars                           
		KZT = 78, //	Kazakstan, Tenge                                  
		LAK = 79, //	Laos, Kips                                        
		LBP = 80, //	Lebanon, Pounds                                   
		LKR = 81, //	Sri Lanka, Rupees                                 
		LRD = 82, //	Liberia, Dollars                                  
		LSL = 83, //	Lesotho, Maloti                                   
		LTL = 84, //	Lithuania, Litai                                  
		LVL = 85, //	Latvia, Lati                                      
		LYD = 86, //	Libya, Dinars                                     
		MAD = 87, //	Morocco, Dirhams                                  
		MDL = 88, //	Moldova, Lei                                      
		MGF = 89, //	Madagascar, Malagasy Francs                       
		MKD = 90, //	Macedonia, Denars                                 
		MMK = 91, //	Myanmar (Burma), Kyats                            
		MNT = 92, //	Mongolia, Tugriks                                 
		MOP = 93, //	Macau, Patacas                                    
		MRO = 94, //	Mauritania, Ouguiyas                              
		MTL = 95, //	Malta, Liri                                       
		MUR = 96, //	Mauritius, Rupees                                 
		MVR = 97, //	Maldives (Maldive Islands), Rufiyaa               
		MWK = 98, //	Malawi, Kwachas                                   
		MXN = 99, //	Mexico, Pesos                                     
		MYR = 100, //	Malaysia, Ringgits                                
		MZM = 101, //	Mozambique, Meticais                              
		NAD = 102, //	Namibia, Dollars                                  
		NGN = 103, //	Nigeria, Nairas                                   
		NIO = 104, //	Nicaragua, Gold Cordobas                          
		NOK = 105, //	Norway, Krone                                     
		NPR = 106, //	Nepal, Nepal Rupees                               
		NZD = 107, //	New Zealand, Dollars                              
		OMR = 108, //	Oman, Rials                                       
		PAB = 109, //	Panama, Balboa                                    
		PEN = 110, //	Peru, Nuevos Soles                                
		PGK = 111, //	Papua New Guinea, Kina                            
		PHP = 112, //	Philippines, Pesos                                
		PKR = 113, //	Pakistan, Rupees                                  
		PLN = 114, //	Poland, Zlotych                                   
		PYG = 115, //	Paraguay, Guarani                                 
		QAR = 116, //	Qatar, Rials                                      
		ROL = 117, //	Romania, Lei                                      
		RUR = 118, //	Russia, Rubles                                    
		RWF = 119, //	Rwanda, Rwanda Francs                             
		SAR = 120, //	Saudi Arabia, Riyals                              
		SBD = 121, //	Solomon Islands, Dollars                          
		SCR = 122, //	Seychelles, Rupees                                
		SDD = 123, //	Sudan, Dinars                                     
		SEK = 124, //	Sweden, Kronor                                    
		SGD = 125, //	Singapore, Dollars                                
		SHP = 126, //	Saint Helena, Pounds                              
		SIT = 127, //	Slovenia, Tolars                                  
		SKK = 128, //	Slovakia, Koruny                                  
		SLL = 129, //	Sierra Leone, Leones                              
		SOS = 130, //	Somalia, Shillings                                
		SRG = 131, //	Suriname, Guilders                                
		STD = 132, //	São Tome and Principe, Dobras                     
		SVC = 133, //	El Salvador, Colones                              
		SYP = 134, //	Syria, Pounds                                     
		SZL = 135, //	Swaziland, Emalangeni                             
		THB = 136, //	Thailand, Baht                                    
		TJR = 137, //	Tajikistan, Rubles                                
		TMM = 138, //	Turkmenistan, Manats                              
		TND = 139, //	Tunisia, Dinars                                   
		TOP = 140, //	Tonga, Pa'anga                                    
		TRL = 141, //	Turkey, Liras                                     
		TTD = 142, //	Trinidad and Tobago, Dollars                      
		TWD = 143, //	Taiwan, New Dollars                               
		TZS = 144, //	Tanzania, Shillings                               
		UAH = 145, //	Ukraine, Hryvnia                                  
		UGX = 146, //	Uganda, Shillings                                 
		USD = 147, //	United States of America, Dollars                 
		UYU = 148, //	Uruguay, Pesos                                    
		UZS = 149, //	Uzbekistan, Sums                                  
		VEB = 150, //	Venezuela, Bolivares                              
		VND = 151, //	Viet Nam, Dong                                    
		VUV = 152, //	Vanuatu, Vatu                                     
		WST = 153, //	Samoa, Tala                                       
		XAF = 154, //	Communauté Financière Africaine BEA               
		XCD = 155, //	East Caribbean Dollars                            
		XDR = 156, //	International Monetary Fund (IMF) S               
		XOF = 157, //	Communauté Financière Africaine BCE               
		XPF = 158, //	Comptoirs Français du Pacifique Fra               
		YER = 159, //	Yemen, Rials                                      
		YUM = 160, //	Yugoslavia, New Dinars                            
		ZAR = 161, //	South Africa, Rand                                
		ZMK = 162, //	Zambia, Kwacha                                    
		ZWD = 163 //	Zimbabwe, Zimbabwe Dollars                        
	}
}