import {FrameworkConfiguration, PLATFORM} from 'aurelia-framework';

export function configure(config: FrameworkConfiguration) {
  config.globalResources([PLATFORM.moduleName("./pager/pager")]);
  config.globalResources([PLATFORM.moduleName("./reporting-frequency-selector/reporting-frequency-selector")]);
  config.globalResources([PLATFORM.moduleName("./reporting-term-selector/reporting-term-selector")]);
  config.globalResources([PLATFORM.moduleName("./organization-selector/organization-selector")]);
  config.globalResources([PLATFORM.moduleName("./organization-type-selector/organization-type-selector")]);
  config.globalResources([PLATFORM.moduleName("./organization-role-type-selector/organization-role-type-selector")]);
  config.globalResources([PLATFORM.moduleName("./report-status-selector/report-status-selector")]);
  config.globalResources([PLATFORM.moduleName("./money-selector/money-selector")]);
  config.globalResources([PLATFORM.moduleName("./input-number/input-number")]);
  config.globalResources([PLATFORM.moduleName("./library-this-period/library-this-period")]);
  config.globalResources([PLATFORM.moduleName("./value-converters/NumberValueConverter")]);
  config.globalResources([PLATFORM.moduleName("./value-converters/OrganizationTypeValueConverter")]);
  config.globalResources([PLATFORM.moduleName("./value-converters/ReportingFrequencyValueConverter")]);
  config.globalResources([PLATFORM.moduleName("./value-converters/ReportingPeriodValueConverter")]);
  config.globalResources([PLATFORM.moduleName("./value-converters/ConvertToLocalDateValueConverter")]);
  config.globalResources([PLATFORM.moduleName("./value-converters/ConvertToLocalDateOnlyValueConverter")]);
  config.globalResources([PLATFORM.moduleName("./value-converters/ReportingTermValueConverter")]);
  config.globalResources([PLATFORM.moduleName("./value-converters/ReportPlanStatusValueConverter")]);
  config.globalResources([PLATFORM.moduleName("./value-converters/ReportStatusValueConverter")]);
  config.globalResources([PLATFORM.moduleName("./value-converters/CanEditPlanValueConverter")]);
  config.globalResources([PLATFORM.moduleName("./value-converters/CanViewReportValueConverter")]);
  config.globalResources([PLATFORM.moduleName("./value-converters/CanEditReportValueConverter")]);
  config.globalResources([PLATFORM.moduleName("./value-converters/MoneyValueConverter")]);
  config.globalResources([PLATFORM.moduleName("./value-converters/ReportingPeriodViewModelValueConverter")]);
  config.globalResources([PLATFORM.moduleName("./numeric-only-attribute/numeric-only-attribute")]);
  config.globalResources([PLATFORM.moduleName("./decimal-only-attribute/decimal-only-attribute")]);
  config.globalResources([PLATFORM.moduleName("./member-data-this-period/member-data-this-period")]);
  config.globalResources([PLATFORM.moduleName("./plan-report-header/plan-report-header")]);
  config.globalResources([PLATFORM.moduleName("./plan-report-shell/plan-report-shell")]);
  config.globalResources([PLATFORM.moduleName("./plan-manpower-view/plan-manpower-view")]);
  config.globalResources([PLATFORM.moduleName("./plan-manpower-edit/plan-manpower-edit")]);
  config.globalResources([PLATFORM.moduleName("./plan-regular-meetings-view/plan-regular-meetings-view")]);
  config.globalResources([PLATFORM.moduleName("./plan-regular-meetings-edit/plan-regular-meetings-edit")]);
  config.globalResources([PLATFORM.moduleName("./plan-teaching-view/plan-teaching-view")]);
  config.globalResources([PLATFORM.moduleName("./plan-teaching-edit/plan-teaching-edit")]);
  config.globalResources([PLATFORM.moduleName("./plan-socialwelfare-view/plan-socialwelfare-view")]);
  config.globalResources([PLATFORM.moduleName("./plan-socialwelfare-edit/plan-socialwelfare-edit")]);
  config.globalResources([PLATFORM.moduleName("./plan-material-view/plan-material-view")]);
  config.globalResources([PLATFORM.moduleName("./plan-material-edit/plan-material-edit")]);
  config.globalResources([PLATFORM.moduleName("./plan-finance-view/plan-finance-view")]);
  config.globalResources([PLATFORM.moduleName("./plan-finance-edit/plan-finance-edit")]);
  config.globalResources([PLATFORM.moduleName("./report-manpower-view/report-manpower-view")]);
  config.globalResources([PLATFORM.moduleName("./report-manpower-edit/report-manpower-edit")]);
  config.globalResources([PLATFORM.moduleName("./report-regular-meetings-view/report-regular-meetings-view")]);
  config.globalResources([PLATFORM.moduleName("./report-regular-meetings-edit/report-regular-meetings-edit")]);
  config.globalResources([PLATFORM.moduleName("./report-teaching-view/report-teaching-view")]);
  config.globalResources([PLATFORM.moduleName("./report-teaching-edit/report-teaching-edit")]);
  config.globalResources([PLATFORM.moduleName("./report-socialwelfare-view/report-socialwelfare-view")]);
  config.globalResources([PLATFORM.moduleName("./report-socialwelfare-edit/report-socialwelfare-edit")]);
  config.globalResources([PLATFORM.moduleName("./report-material-view/report-material-view")]);
  config.globalResources([PLATFORM.moduleName("./report-material-edit/report-material-edit")]);
  config.globalResources([PLATFORM.moduleName("./report-library-view/report-library-view")]);
  config.globalResources([PLATFORM.moduleName("./report-library-edit/report-library-edit")]);
  config.globalResources([PLATFORM.moduleName("./report-finance-view/report-finance-view")]);
  config.globalResources([PLATFORM.moduleName("./report-finance-edit/report-finance-edit")]);
  config.globalResources([PLATFORM.moduleName("./finance-balance/finance-balance")]);
  config.globalResources([PLATFORM.moduleName("./finance-worker-promise-this-period/finance-worker-promise-this-period")]);
  config.globalResources([PLATFORM.moduleName("./reporting-period-selector/reporting-period-selector")]);
  config.globalResources([
    PLATFORM.moduleName("./report-manpower-lastperiod-edit/report-manpower-lastperiod-edit"),
    PLATFORM.moduleName("./report-finance-lastperiod-edit/report-finance-lastperiod-edit"),
    PLATFORM.moduleName("./report-library-lastperiod-edit/report-library-lastperiod-edit")
  ]);
}
