import { MeetingProgramReportData } from "./MeetingProgramReportData";
import { MemberReportData } from "./MemberReportData";
import { TeachingLearningProgramData } from "./TeachingLearningProgramData";
import { LibraryStockData } from "./LibraryStockData";
import { MaterialData } from "./MaterialData";
import { FinanceReportData } from "./FinanceReportData";
import { SocialWelfareReportData } from "./SocialWelfareReportData";

export class ReportUpdateData {
    constructor(public associateMemberReportData: MemberReportData,
        public preliminaryMemberReportData: MemberReportData,
        public supporterMemberReportData: MemberReportData,
        public memberMemberReportData: MemberReportData,
        public workerMeetingProgramReportData: MeetingProgramReportData,
        public cmsMeetingProgramReportData: MeetingProgramReportData,
        public smMeetingProgramReportData: MeetingProgramReportData,
        public memberMeetingProgramReportData: MeetingProgramReportData,
        public dawahMeetingProgramReportData: MeetingProgramReportData,
        public stateLeaderMeetingProgramReportData: MeetingProgramReportData,
        public stateOutingMeetingProgramReportData: MeetingProgramReportData,
        public iftarMeetingProgramReportData: MeetingProgramReportData,
        public learningMeetingProgramReportData: MeetingProgramReportData,
        public socialDawahMeetingProgramReportData: MeetingProgramReportData,
        public dawahGroupMeetingProgramReportData: MeetingProgramReportData,
        public nextGMeetingProgramReportData: MeetingProgramReportData,
        public tafsirMeetingProgramReportData: MeetingProgramReportData,
        public unitMeetingProgramReportData: MeetingProgramReportData,
        public bbqMeetingProgramReportData: MeetingProgramReportData,
        public gatheringMeetingProgramReportData: MeetingProgramReportData,
        public familyVisitMeetingProgramReportData: MeetingProgramReportData,
        public eidReunionMeetingProgramReportData: MeetingProgramReportData,
        public otherMeetingProgramReportData: MeetingProgramReportData,
        public groupStudyTeachingLearningProgramReportData: TeachingLearningProgramData,
        public studyCircleForAssociateMemberTeachingLearningProgramReportData: TeachingLearningProgramData,
        public studyCircleTeachingLearningProgramReportData: TeachingLearningProgramData,
        public practiceDarsTeachingLearningProgramReportData: TeachingLearningProgramData,
        public stateLearningCampTeachingLearningProgramReportData: TeachingLearningProgramData,
        public quranStudyTeachingLearningProgramReportData: TeachingLearningProgramData,
        public hadithTeachingLearningProgramReportData: TeachingLearningProgramData,
        public quranClassTeachingLearningProgramReportData: TeachingLearningProgramData,
        public weekendIslamicSchoolTeachingLearningProgramReportData: TeachingLearningProgramData,
        public memorizingAyatTeachingLearningProgramReportData: TeachingLearningProgramData,
        public memorizingHadithTeachingLearningProgramReportData: TeachingLearningProgramData,
        public memorizingDoaTeachingLearningProgramReportData: TeachingLearningProgramData,
        public stateLearningSessionTeachingLearningProgramReportData: TeachingLearningProgramData,
        public stateQiyamulLailTeachingLearningProgramReportData: TeachingLearningProgramData,  
        public otherTeachingLearningProgramReportData: TeachingLearningProgramData,       
        public qardeHasanaSocialWelfareReportData: SocialWelfareReportData,
        public patientVisitSocialWelfareReportData: SocialWelfareReportData,
        public socialVisitSocialWelfareReportData: SocialWelfareReportData,
        public transportSocialWelfareReportData: SocialWelfareReportData,
        public shiftingSocialWelfareReportData: SocialWelfareReportData,
        public shoppingSocialWelfareReportData: SocialWelfareReportData,
        public foodDistributionSocialWelfareReportData: SocialWelfareReportData,
        public cleanUpAustraliaSocialWelfareReportData: SocialWelfareReportData,
        public otherSocialWelfareReportData: SocialWelfareReportData,
        public bookSaleMaterialReportData: MaterialData,
        public bookDistributionMaterialReportData: MaterialData,
        public vhsSaleMaterialReportData: MaterialData,
        public vhsDistributionMaterialReportData: MaterialData,
        public emailDistributionMaterialReportData: MaterialData,
        public ipdcLeafletDistributionMaterialReportData: MaterialData,
        public otherSaleMaterialReportData: MaterialData,
        public otherDistributionMaterialReportData: MaterialData,
        public bookLibraryStockReportData: LibraryStockData,
        public vhsLibraryStockReportData: LibraryStockData,
        public otherLibraryStockReportData: LibraryStockData,
        public baitulMalFinanceReportData: FinanceReportData,
        public aDayMasjidProjectFinanceReportData: FinanceReportData,
        public masjidTableBankFinanceReportData: FinanceReportData,
        public comment: string) { }
}
