import { OrganizationReference } from "./OrganizationReference";
import { ReportingPeriod } from "./ReportingPeriod";
import { ReportStatus } from "./ReportStatus";
import { ReopenedReportStatus } from "./ReopenedReportStatus";
import { MemberPlanData } from "./MemberPlanData";
import { MeetingProgramPlanData } from "./MeetingProgramPlanData";
import { TeachingLearningProgramPlanData } from "./TeachingLearningProgramPlanData";
import { MaterialPlanData } from "./MaterialPlanData";
import { FinancePlanData } from "./FinancePlanData";
import { SocialWelfarePlanData } from "./SocialWelfarePlanData";

export class StatePlanViewModelDto {
    constructor(public id: number,
        public description: string,
        public organization: OrganizationReference,
        public reportingPeriod: ReportingPeriod,
        public reportStatus: ReportStatus,
        public reportStatusDescription: string,
        public reOpenedReportStatus: ReopenedReportStatus,
        public reOpenedReportStatusDescription: string,
        public associateMemberPlanData: MemberPlanData,
        public associateMemberPlanGeneratedData: MemberPlanData,
        public preliminaryMemberPlanData: MemberPlanData,
        public preliminaryMemberPlanGeneratedData: MemberPlanData,
        public supporterMemberPlanData: MemberPlanData,
        public supporterMemberPlanGeneratedData: MemberPlanData,
        public memberMemberPlanData: MemberPlanData,
        public memberMemberPlanGeneratedData: MemberPlanData,
        public workerMeetingProgramPlanData: MeetingProgramPlanData,
        public workerMeetingProgramPlanGeneratedData: MeetingProgramPlanData,
        public cmsMeetingProgramPlanData: MeetingProgramPlanData,
        public cmsMeetingProgramPlanGeneratedData: MeetingProgramPlanData,
        public smMeetingProgramPlanData: MeetingProgramPlanData,
        public smMeetingProgramPlanGeneratedData: MeetingProgramPlanData,
        public memberMeetingProgramPlanData: MeetingProgramPlanData,
        public memberMeetingProgramPlanGeneratedData: MeetingProgramPlanData,
        public dawahMeetingProgramPlanData: MeetingProgramPlanData,
        public dawahMeetingProgramPlanGeneratedData: MeetingProgramPlanData,
        public stateLeaderMeetingProgramPlanData: MeetingProgramPlanData,
        public stateLeaderMeetingProgramPlanGeneratedData: MeetingProgramPlanData,
        public stateOutingMeetingProgramPlanData: MeetingProgramPlanData,
        public stateOutingMeetingProgramPlanGeneratedData: MeetingProgramPlanData,
        public iftarMeetingProgramPlanData: MeetingProgramPlanData,
        public iftarMeetingProgramPlanGeneratedData: MeetingProgramPlanData,
        public learningMeetingProgramPlanData: MeetingProgramPlanData,
        public learningMeetingProgramPlanGeneratedData: MeetingProgramPlanData,
        public socialDawahMeetingProgramPlanData: MeetingProgramPlanData,
        public socialDawahMeetingProgramPlanGeneratedData: MeetingProgramPlanData,
        public dawahGroupMeetingProgramPlanData: MeetingProgramPlanData,
        public dawahGroupMeetingProgramPlanGeneratedData: MeetingProgramPlanData,
        public nextGMeetingProgramPlanData: MeetingProgramPlanData,
        public nextGMeetingProgramPlanGeneratedData: MeetingProgramPlanData,
        public tafsirMeetingProgramPlanData: MeetingProgramPlanData,
        public tafsirMeetingProgramPlanGeneratedData: MeetingProgramPlanData,
        public unitMeetingProgramPlanData: MeetingProgramPlanData,
        public unitMeetingProgramPlanGeneratedData: MeetingProgramPlanData,
        public bbqMeetingProgramPlanData: MeetingProgramPlanData,
        public bbqMeetingProgramPlanGeneratedData: MeetingProgramPlanData,
        public gatheringMeetingProgramPlanData: MeetingProgramPlanData,
        public gatheringMeetingProgramPlanGeneratedData: MeetingProgramPlanData,
        public familyVisitMeetingProgramPlanData: MeetingProgramPlanData,
        public familyVisitMeetingProgramPlanGeneratedData: MeetingProgramPlanData,
        public eidReunionMeetingProgramPlanData: MeetingProgramPlanData,
        public eidReunionMeetingProgramPlanGeneratedData: MeetingProgramPlanData,
        public otherMeetingProgramPlanData: MeetingProgramPlanData,
        public otherMeetingProgramPlanGeneratedData: MeetingProgramPlanData,
        public groupStudyTeachingLearningProgramPlanData: TeachingLearningProgramPlanData,
        public groupStudyTeachingLearningProgramPlanGeneratedData: TeachingLearningProgramPlanData,
        public studyCircleForAssociateMemberTeachingLearningProgramPlanData: TeachingLearningProgramPlanData,
        public studyCircleForAssociateMemberTeachingLearningProgramPlanGeneratedData: TeachingLearningProgramPlanData,
        public studyCircleTeachingLearningProgramPlanData: TeachingLearningProgramPlanData,
        public studyCircleTeachingLearningProgramPlanGeneratedData: TeachingLearningProgramPlanData,
        public practiceDarsTeachingLearningProgramPlanData: TeachingLearningProgramPlanData,
        public practiceDarsTeachingLearningProgramPlanGeneratedData: TeachingLearningProgramPlanData,
        public stateLearningCampTeachingLearningProgramPlanData: TeachingLearningProgramPlanData,
        public stateLearningCampTeachingLearningProgramPlanGeneratedData: TeachingLearningProgramPlanData,
        public quranStudyTeachingLearningProgramPlanData: TeachingLearningProgramPlanData,
        public quranStudyTeachingLearningProgramPlanGeneratedData: TeachingLearningProgramPlanData,
        public hadithTeachingLearningProgramPlanData: TeachingLearningProgramPlanData,
        public hadithTeachingLearningProgramPlanGeneratedData: TeachingLearningProgramPlanData,
        public quranClassTeachingLearningProgramPlanData: TeachingLearningProgramPlanData,
        public quranClassTeachingLearningProgramPlanGeneratedData: TeachingLearningProgramPlanData,
        public weekendIslamicSchoolTeachingLearningProgramPlanData: TeachingLearningProgramPlanData,
        public weekendIslamicSchoolTeachingLearningProgramPlanGeneratedData: TeachingLearningProgramPlanData,
        public memorizingAyatTeachingLearningProgramPlanData: TeachingLearningProgramPlanData,
        public memorizingAyatTeachingLearningProgramPlanGeneratedData: TeachingLearningProgramPlanData,
        public memorizingHadithTeachingLearningProgramPlanData: TeachingLearningProgramPlanData,
        public memorizingHadithTeachingLearningProgramPlanGeneratedData: TeachingLearningProgramPlanData,
        public memorizingDoaTeachingLearningProgramPlanData: TeachingLearningProgramPlanData,
        public memorizingDoaTeachingLearningProgramPlanGeneratedData: TeachingLearningProgramPlanData,
        public stateLearningSessionTeachingLearningProgramPlanData: TeachingLearningProgramPlanData,
        public stateLearningSessionTeachingLearningProgramPlanGeneratedData: TeachingLearningProgramPlanData,
        public stateQiyamulLailTeachingLearningProgramPlanData: TeachingLearningProgramPlanData,
        public stateQiyamulLailTeachingLearningProgramPlanGeneratedData: TeachingLearningProgramPlanData,
        public otherTeachingLearningProgramPlanData: TeachingLearningProgramPlanData,
        public otherTeachingLearningProgramPlanGeneratedData: TeachingLearningProgramPlanData,
        public bookSaleMaterialPlanData: MaterialPlanData,
        public bookSaleMaterialPlanGeneratedData: MaterialPlanData,
        public bookDistributionMaterialPlanData: MaterialPlanData,
        public bookDistributionMaterialPlanGeneratedData: MaterialPlanData,
        public vhsSaleMaterialPlanData: MaterialPlanData,
        public vhsSaleMaterialPlanGeneratedData: MaterialPlanData,
        public vhsDistributionMaterialPlanData: MaterialPlanData,
        public vhsDistributionMaterialPlanGeneratedData: MaterialPlanData,
        public emailDistributionMaterialPlanData: MaterialPlanData,
        public emailDistributionMaterialPlanGeneratedData: MaterialPlanData,
        public ipdcLeafletDistributionMaterialPlanData: MaterialPlanData,
        public ipdcLeafletDistributionMaterialPlanGeneratedData: MaterialPlanData,
        public otherSaleMaterialPlanData: MaterialPlanData,
        public otherSaleMaterialPlanGeneratedData: MaterialPlanData,
        public otherDistributionMaterialPlanData: MaterialPlanData,
        public otherDistributionMaterialPlanGeneratedData: MaterialPlanData,
        public baitulMalFinancePlanData: FinancePlanData,
        public baitulMalFinancePlanGeneratedData: FinancePlanData,
        public aDayMasjidProjectFinancePlanData: FinancePlanData,
        public aDayMasjidProjectFinancePlanGeneratedData: FinancePlanData,
        public masjidTableBankFinancePlanData: FinancePlanData,
        public masjidTableBankFinancePlanGeneratedData: FinancePlanData,
        public qardeHasanaSocialWelfarePlanData: SocialWelfarePlanData,
        public qardeHasanaSocialWelfarePlanGeneratedData: SocialWelfarePlanData,
        public patientVisitSocialWelfarePlanData: SocialWelfarePlanData,
        public patientVisitSocialWelfarePlanGeneratedData: SocialWelfarePlanData,
        public socialVisitSocialWelfarePlanData: SocialWelfarePlanData,
        public socialVisitSocialWelfarePlanGeneratedData: SocialWelfarePlanData,
        public transportSocialWelfarePlanData: SocialWelfarePlanData,
        public transportSocialWelfarePlanGeneratedData: SocialWelfarePlanData,
        public shiftingSocialWelfarePlanData: SocialWelfarePlanData,
        public shiftingSocialWelfarePlanGeneratedData: SocialWelfarePlanData,
        public shoppingSocialWelfarePlanData: SocialWelfarePlanData,
        public shoppingSocialWelfarePlanGeneratedData: SocialWelfarePlanData,
        public foodDistributionSocialWelfarePlanData: SocialWelfarePlanData,
        public foodDistributionSocialWelfarePlanGeneratedData: SocialWelfarePlanData,
        public cleanUpAustraliaSocialWelfarePlanData: SocialWelfarePlanData,
        public cleanUpAustraliaSocialWelfarePlanGeneratedData: SocialWelfarePlanData,
        public otherSocialWelfarePlanData: SocialWelfarePlanData,
        public otherSocialWelfarePlanGeneratedData: SocialWelfarePlanData,
        public timestamp: Date){}
}
